asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
  - idseparator=_
  - source-highlighter=coderay
  - icons=font
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
