---
layout: post
title:  "Documenteren, de weg naar het beschrijven"
categories: requirements documenteren beschrijven agile
excerpt: "Vanuit watervalachtige methodieken zijn we gewend documenten op te stellen. Deze focus op documenten zit het effectief beschrijven van de software voor de eindgebruikers in de weg."
---
== Meer _agile_ werken

Gedurende de laatste jaren hebben we veel verandering teweeg kunnen brengen in de manier waarop we werken. Vanuit de "_agile_" gedachte zijn we in gesprek gegaan met de eindgebruikers, hebben we in kleine iteraties software opgeleverd en hebben we de reacties gebruikt voor de volgende kleine iteratie. De _documentatie_ die we opleveren kent echter een ander ontwikkelproces. Vaak wordt achteraf, na een aantal iteraties, geconstateerd dat de documentatie gedateerd is en een update nodig heeft. In een enkel geval is het updaten van de documentatie een onderdeel van de "definition of done" voor een iteratie en sluit zodoende beter aan bij de gedachte achter een wendbare werkwijze. De keuze voor wat er aangepast moet worden doen we op basis van ons eigen inzicht: geen gebruiker wordt gevraagd wat er in de documenten moet komen.

Er zijn afspraken omtrent de documentatie die we moeten opleveren, gebaseerd op een oudere standaard (J-STD) en een zogenoemde _algemene software engineering praktijk_, wat in de praktijk neerkomt op de volgende richtlijn voor op te leveren documenten.

* Requirements document *
* Functioneel ontwerp *
* Technisch ontwerp
* Technische documentatie / systeemdocumentatie
* Testplan
* Testrapport / validatierapport
* Installatiehandleiding
* Gebruikershandleiding

*) Het requirements document en functioneel ontwerp mogen samengevoegd worden.

Als we kijken naar de beschrijving van de J-STD standaard, dan beschrijft men daar dat besproken moet worden tussen opdrachtgever en opdrachtnemer, welke _software producten_ opgeleverd moeten worden en wat de inhoud ervan moet zijn, zodat alleen de nodige en kosten-efficiënte eisen worden toegepast. Aangezien er geen afspraken te vinden zijn over de _software producten_ en de vereiste inhoud, kan geconcludeerd worden dat dergelijke afspraken niet zijn gemaakt.

Als we kijken naar de algemene software engineering praktijk, dan is op te merken dat het functioneel ontwerp en het technisch ontwerp een onderdeel van overdracht zijn van de architect richting de ontwikkelaars in een meer waterval-georiënteerde ontwikkelmethodiek. Het functioneel ontwerp beschrijft de (niet) functionele eisen die worden gesteld aan het systeem, op basis van de features die zijn gedefinieerd met als doel het realiseren van de doelen van de gebruiker. Het technisch ontwerp vertaalt de (niet) functionele eisen naar een beschrijving van de benodigde implementatie. De manier van vooraf de (niet) functionele eisen en technische implementatie beschrijven is dus tegenstrijdig met de manier waarop de documentatie op dit moment, na ontwikkeling, wordt geüpdatet. Ook kan dus geconcludeerd worden dat de doelgroep van het functioneel ontwerp en het technisch ontwerp voor gebruik in het de waterval-georiënteerde methodiek anders moet zijn dan de doelgroep van de door ons opgeleverde documenten. Maar wie is dán de doelgroep van onze documentatie?

[quote]
Onze manier van documentatie is niet kosten efficiënt en niet toegespitst op het beoogde gebruik ervan.

Een veelgehoord beoogd doel is het mogelijk maken dat de ontwikkeling van producten overdraagbaar is. Met andere woorden, wanneer een nieuw team verder gaat met de ontwikkeling van een product, dan moeten het functionele ontwerp document en het technisch ontwerp document gebruikt kunnen worden om dit te versoepelen. Sommigen zouden ook willen dat de documentatie aan nieuwe ontwikkelaars overgedragen kan worden, zodat zij na kennisneming meteen aan de slag kunnen. Vaak bevat de documentatie echter wel beschrijvingen van een gewenste situatie, maar de belangrijke afwijkingen op het ontwerp vinden juist niet vaak hun weg terug naar documentatie. Het zijn juist deze afwijkingen die belangrijk zijn om te onderkennen bij de verdere ontwikkeling.

== Beschrijven

Naast het doel om de ontwikkeling van het product over te kunnen dragen aan een nieuw team of nieuwe teamleden, is er een ander doel dat hieraan gerelateerd is, niet veel genoemd wordt in de discussie over documentatie, maar wel veel ter sprake komt tijdens de ontwikkeling van producten: het overdragen van de ontwikkeling van het product binnen het team, en zelfs de "toekomstige ik". De oplossingen kenmerken zich door de acceptatie van het veranderende karakter van implementaties. Daarom worden beschrijvingen zo dicht mogelijk bij hetgeen dat wordt beschreven gehouden, zodat de kans dat de beschrijving wordt geüpdatet bij een wijziging groter is. Ook wordt de intentie, het wat, beschreven in plaats van de manier waarop het doel gerealiseerd is, het hoe. Bij een juiste toepassing van beschrijvingen, kunnen tevens tools gebruikt worden om de beschrijvingen nog toegankelijker te maken. Daarnaast helpt het om een door het hele ontwikkelteam gedragen manier van ontwikkelen te handhaven en deze ook iteratief te onderhouden. De ervaring leert dat door de focus aan te brengen op zelf beschrijvende implementaties, ook nieuwe ontwikkelaars zichzelf snel comfortabel voelen om met de code te werken.

Tijdens de ontwikkeling wordt natuurlijk ook nagedacht over de functionaliteit die geïmplementeerd moet worden. In plaats van het volledig uitwerken van een functioneel ontwerp, wordt ook het proces rond het uitwerken van (niet) functionele eisen gekenmerkt door het veranderende karakter van de omgeving, waaronder stakeholders. Grote functionele concepten die doelen van gebruikers beschrijven, worden tijdens de ontwikkeling verfijnd tot (niet) functionele eigenschappen van het systeem die samen de gebruiker ondersteunt in het bereiken van deze doelen. Deze beschrijvingen vormen samen in feite het functionele ontwerp.

Dit is meestal het niveau van waaruit de ontwikkeling start. Het is echter mogelijk om een brug te slaan tussen functionele en technische beschrijvingen, waardoor de code ook zichzelf functioneel zou kunnen beschrijven. Deze methode, genaamd Behavior Driven Development, laat ontwikkelaars en stakeholders samen user stories verder uitwerken in scenario's. BDD tools stellen de ontwikkelaars vervolgens in staat om de scenario's in code te definiëren. Vanaf dit punt kunnen de scenario's verder worden uitgewerkt richting implementatie, maar ook uitgevoerd worden en met resultaat geaggregeerd worden in een rapport.

== Conclusie

Er zijn in het verleden aannames gedaan: de J-STD standaard schrijft een aantal documenten voor, het functioneel ontwerp en technisch ontwerp zoals opgeleverd en overgedragen aan een ontwikkelteam is bruikbaar voor verdere ontwikkeling, en documentatie van software bestaat uitsluitend uit documenten.

In dit artikel is geprobeerd duidelijk te maken dat de huidige vorm van op te leveren documentatie niet is voortgekomen uit een concrete wens van beoogde doelgroepen, maar gebaseerd is op een methodiek die we zelf niet volgen. Er zijn technieken die veel beter toe te passen zijn in de methodiek die we volgen, en hoewel deze niet resulteren in documenten, beschrijven ze wel beter op een functioneel en technisch niveau wat heeft geleid tot het opgeleverde product. En hoewel het voornaamste doel van deze technieken is om als ontwikkelteam zelf beter in staat te zijn om met vertrouwen wijzigingen aan te brengen in de implementatie, resulteert dit ook in begrijpbaarheid van de implementatie van buiten het huidigen ontwikkelteam.

P.S. ik kan me voorstellen dat men denkt dat beschrijvingen die door ontwikkelaars worden opgesteld alleen maar te begrijpen is voor ontwikkelaars in het team. Dit is echter een risico bij iedere vorm van beschrijvingen die niet wordt getoetst bij de beoogde doelgroep.